language: java
jdk:
  - openjdk11

# Git Push할 Branch
branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build -x test"

before_deploy:
  - zip -r hometact-backend *
  - mkdir -p deploy
  - mv hometact-backend.zip deploy/hometact-backend.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: hometact-deploy # 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    on:
      repo: dongkyunkimdev/hometact-backend #Github 주소
      branch: master

  - provider: codedeploy
      access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
      secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
      bucket: hometact-deploy # S3 버킷
      key: hometact-backend.zip # S3 버킷에 저장된 jaewon-study.zip 파일을 EC2로 배포
      bundle_type: zip
      application: devkim-study-webservice # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
      deployment_group: devkim-study-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
      region: ap-northeast-2
      wait-until-deployed: true
      on:
        repo: dongkyunkimdev/hometact-backend #Github 주소
        branch: master

before_install:
  - chmod +x gradlew

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - ddkds66@gmail.com

