spring:
  profiles:
    default: prod

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    kdk: INFO

jwt:
  header: Authorization
  secret: a2RrLXRlY2gtc3ByaW5nLWJvb3Qtand0LXR1dG9yaWFsLXNlY3JldC1rZGstdGVjaC1zcHJpbmctYm9vdC1qd3QtdHV0b3JpYWwtc2VjcmV0
  access-token-validity-in-seconds: 600
  refresh-token-validity-in-seconds: 604800

server:
  port: 8080