spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mariadb://aws-rds:3306/hometact
    driver-class-name: org.mariadb.jdbc.Driver
    username: username
    password: password