spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: hometact.cidyenzm1vnz.ap-northeast-2.rds.amazonaws.com
    driver-class-name: org.mariadb.jdbc.Driver
    username: hometact
    password: kdk0490