INSERT INTO AUTHORITY (AUTHORITY_NAME) VALUES ('ROLE_USER');
INSERT INTO AUTHORITY (AUTHORITY_NAME) VALUES ('ROLE_ADMIN');

INSERT INTO USER (CREATED_DATE, MODIFIED_DATE, EMAIL, NICKNAME, PASSWORD) VALUES (NOW(), NOW(), 'admin@admin.com', 'admin', '$2a$10$mEPI8UAjGX2UIdB1NUwr5.e6fzAHx7p81HfMkYAQGhcmYcGBBBa9q');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) VALUES (1, 'ROLE_ADMIN');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) VALUES (1, 'ROLE_USER');

INSERT INTO POST_CATEGORY (CATEGORY_NAME) VALUES ('독서');
INSERT INTO POST_CATEGORY (CATEGORY_NAME) VALUES ('영화');
INSERT INTO POST_CATEGORY (CATEGORY_NAME) VALUES ('게임');
INSERT INTO POST_CATEGORY (CATEGORY_NAME) VALUES ('공예');
INSERT INTO POST_CATEGORY (CATEGORY_NAME) VALUES ('기타');