INSERT INTO authority (AUTHORITY_NAME) VALUES ('ROLE_USER');
INSERT INTO authority (AUTHORITY_NAME) VALUES ('ROLE_ADMIN');

INSERT INTO user (CREATED_DATE, MODIFIED_DATE, EMAIL, NICKNAME, PASSWORD) VALUES (NOW(), NOW(), 'admin@admin.com', 'admin', '$2a$10$mEPI8UAjGX2UIdB1NUwr5.e6fzAHx7p81HfMkYAQGhcmYcGBBBa9q');
INSERT INTO user_authority (USER_ID, AUTHORITY_NAME) VALUES (1, 'ROLE_ADMIN');
INSERT INTO user_authority (USER_ID, AUTHORITY_NAME) VALUES (1, 'ROLE_USER');

INSERT INTO post_category (CATEGORY_NAME) VALUES ('독서');
INSERT INTO post_category (CATEGORY_NAME) VALUES ('영화');
INSERT INTO post_category (CATEGORY_NAME) VALUES ('게임');
INSERT INTO post_category (CATEGORY_NAME) VALUES ('공예');
INSERT INTO post_category (CATEGORY_NAME) VALUES ('기타');